export const questMock = [
    {
        id: 34534534543,
        title: "Test1",
        user_confirmation_required: false,
        frontend_identifier: "quest--xs--test1--ffc",
        strategy: "bet",
        game_category_identity: "pokies",
        start_at: "2024-03-13T00:00:00.000Z",
        end_at: "2025-04-26T23:59:00.000Z",
        finished_at: null,
        currency: "EUR",
        group_tournament: false,
        games_taken_limit: null,
        group_ids: [ 957 ],
        currencies: [
            "EUR",
            "USD",
            "NOK",
            "CAD",
            "NZD",
            "JPY",
            "AUD",
            "BRL",
            "USDC",
            "BTC",
            "ETH",
            "LTC",
            "BCH",
            "DOG",
            "USDT",
            "BNB",
            "TRX",
        ],
        in_progress: true,
        money_budget: "0.00",
        money_budget_cents: 0,
        prizes: [
            {
                id: 32250,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 0,
                nickname: null,
                award_place: 1,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "5000.00",
                money_award_cents: 500000,
            },
            {
                id: 32251,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 2,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "1000.00",
                money_award_cents: 100000,
            },
            {
                id: 32252,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 3,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "700.00",
                money_award_cents: 70000,
            },
            {
                id: 32253,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 4,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "400.00",
                money_award_cents: 40000,
            },
            {
                id: 32254,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 5,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "200.00",
                money_award_cents: 20000,
            },
            {
                id: 32255,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 6,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "150.00",
                money_award_cents: 15000,
            },
            {
                id: 32256,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 7,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "100.00",
                money_award_cents: 10000,
            },
            {
                id: 32257,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 8,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "40.00",
                money_award_cents: 4000,
            },
            {
                id: 32258,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 9,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "20.00",
                money_award_cents: 2000,
            },
            {
                id: 32259,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 10,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "15.00",
                money_award_cents: 1500,
            },
            {
                id: 32260,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 50,
                nickname: null,
                award_place: 11,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32261,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 50,
                nickname: null,
                award_place: 12,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32262,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 30,
                nickname: null,
                award_place: 13,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32263,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 20,
                nickname: null,
                award_place: 14,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32264,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 0,
                nickname: null,
                award_place: 15,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
        ],
        top_players: [
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "1138130.94",
                bet_cents: 113813094,
                wins: "1033438.99",
                win_cents: 103343898,
                points: 0,
                nickname: "Ali",
                award_place: 1,
                award_place_in_team: null,
                games_taken: 161015,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "814102.97",
                bet_cents: 81410296,
                wins: "793333.80",
                win_cents: 79333379,
                points: 0,
                nickname: "David",
                award_place: 2,
                award_place_in_team: null,
                games_taken: 37739,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "674071.91",
                bet_cents: 67407190,
                wins: "666947.82",
                win_cents: 66694781,
                points: 0,
                nickname: "Tracy",
                award_place: 3,
                award_place_in_team: null,
                games_taken: 70579,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "609299.05",
                bet_cents: 60929905,
                wins: "539644.80",
                win_cents: 53964480,
                points: 0,
                nickname: "Mirsada",
                award_place: 4,
                award_place_in_team: null,
                games_taken: 49144,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "583489.49",
                bet_cents: 58348949,
                wins: "555608.22",
                win_cents: 55560822,
                points: 0,
                nickname: "Luckyman",
                award_place: 5,
                award_place_in_team: null,
                games_taken: 25297,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "573769.77",
                bet_cents: 57376977,
                wins: "585774.04",
                win_cents: 58577403,
                points: 0,
                nickname: "Shaneo",
                award_place: 6,
                award_place_in_team: null,
                games_taken: 25353,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "548648.25",
                bet_cents: 54864824,
                wins: "538790.81",
                win_cents: 53879081,
                points: 0,
                nickname: "Barbie",
                award_place: 7,
                award_place_in_team: null,
                games_taken: 33208,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "504818.73",
                bet_cents: 50481873,
                wins: "494795.09",
                win_cents: 49479509,
                points: 0,
                nickname: "Diana",
                award_place: 8,
                award_place_in_team: null,
                games_taken: 51416,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "448403.84",
                bet_cents: 44840384,
                wins: "423017.21",
                win_cents: 42301720,
                points: 0,
                nickname: "Ahmet",
                award_place: 9,
                award_place_in_team: null,
                games_taken: 12716,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "426361.03",
                bet_cents: 42636102,
                wins: "376336.95",
                win_cents: 37633695,
                points: 0,
                nickname: "yun tang",
                award_place: 10,
                award_place_in_team: null,
                games_taken: 20953,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "418853.90",
                bet_cents: 41885390,
                wins: "400558.46",
                win_cents: 40055846,
                points: 0,
                nickname: "Thomas",
                award_place: 11,
                award_place_in_team: null,
                games_taken: 61235,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "401487.74",
                bet_cents: 40148773,
                wins: "409762.75",
                win_cents: 40976275,
                points: 0,
                nickname: "Michael",
                award_place: 12,
                award_place_in_team: null,
                games_taken: 40270,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "392155.44",
                bet_cents: 39215544,
                wins: "390473.17",
                win_cents: 39047317,
                points: 0,
                nickname: "Lachlan",
                award_place: 13,
                award_place_in_team: null,
                games_taken: 29544,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "379418.02",
                bet_cents: 37941802,
                wins: "409834.55",
                win_cents: 40983454,
                points: 0,
                nickname: "Anthony",
                award_place: 14,
                award_place_in_team: null,
                games_taken: 11806,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "346513.90",
                bet_cents: 34651390,
                wins: "372213.07",
                win_cents: 37221307,
                points: 0,
                nickname: "Minhson",
                award_place: 15,
                award_place_in_team: null,
                games_taken: 21606,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "340350.66",
                bet_cents: 34035065,
                wins: "334126.55",
                win_cents: 33412655,
                points: 0,
                nickname: "Scott",
                award_place: 16,
                award_place_in_team: null,
                games_taken: 106403,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "334471.24",
                bet_cents: 33447123,
                wins: "337911.86",
                win_cents: 33791186,
                points: 0,
                nickname: "Tammy7056",
                award_place: 17,
                award_place_in_team: null,
                games_taken: 19347,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "334052.48",
                bet_cents: 33405248,
                wins: "339237.95",
                win_cents: 33923794,
                points: 0,
                nickname: "Andrew",
                award_place: 18,
                award_place_in_team: null,
                games_taken: 25104,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "320977.63",
                bet_cents: 32097762,
                wins: "349122.81",
                win_cents: 34912281,
                points: 0,
                nickname: "Jesus Cristino Burgos",
                award_place: 19,
                award_place_in_team: null,
                games_taken: 11263,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "309564.22",
                bet_cents: 30956422,
                wins: "268708.83",
                win_cents: 26870882,
                points: 0,
                nickname: "Amandeep Singh",
                award_place: 20,
                award_place_in_team: null,
                games_taken: 18144,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "298381.20",
                bet_cents: 29838120,
                wins: "346668.14",
                win_cents: 34666813,
                points: 0,
                nickname: "Nick",
                award_place: 21,
                award_place_in_team: null,
                games_taken: 7094,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "291864.50",
                bet_cents: 29186450,
                wins: "285380.88",
                win_cents: 28538087,
                points: 0,
                nickname: "Rosalyn",
                award_place: 22,
                award_place_in_team: null,
                games_taken: 50638,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "289126.53",
                bet_cents: 28912652,
                wins: "293775.90",
                win_cents: 29377590,
                points: 0,
                nickname: "Coz",
                award_place: 23,
                award_place_in_team: null,
                games_taken: 21988,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "284783.70",
                bet_cents: 28478370,
                wins: "265102.13",
                win_cents: 26510213,
                points: 0,
                nickname: "Jennifer",
                award_place: 24,
                award_place_in_team: null,
                games_taken: 11206,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "284530.71",
                bet_cents: 28453071,
                wins: "282037.00",
                win_cents: 28203700,
                points: 0,
                nickname: "Lindsay",
                award_place: 25,
                award_place_in_team: null,
                games_taken: 17988,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "274011.49",
                bet_cents: 27401149,
                wins: "268258.63",
                win_cents: 26825863,
                points: 0,
                nickname: "Justin",
                award_place: 26,
                award_place_in_team: null,
                games_taken: 15183,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "259179.70",
                bet_cents: 25917969,
                wins: "252036.21",
                win_cents: 25203621,
                points: 0,
                nickname: "Allan",
                award_place: 27,
                award_place_in_team: null,
                games_taken: 16567,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "255872.77",
                bet_cents: 25587277,
                wins: "259138.39",
                win_cents: 25913839,
                points: 0,
                nickname: "Gene",
                award_place: 28,
                award_place_in_team: null,
                games_taken: 12503,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "252536.07",
                bet_cents: 25253606,
                wins: "220261.65",
                win_cents: 22026165,
                points: 0,
                nickname: "Caroline",
                award_place: 29,
                award_place_in_team: null,
                games_taken: 9380,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "251701.41",
                bet_cents: 25170140,
                wins: "266660.13",
                win_cents: 26666012,
                points: 0,
                nickname: "Melissa",
                award_place: 30,
                award_place_in_team: null,
                games_taken: 44852,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "250527.91",
                bet_cents: 25052790,
                wins: "237817.25",
                win_cents: 23781725,
                points: 0,
                nickname: "Spraddy",
                award_place: 31,
                award_place_in_team: null,
                games_taken: 17225,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "246238.17",
                bet_cents: 24623816,
                wins: "249703.53",
                win_cents: 24970353,
                points: 0,
                nickname: "Pamela Hunter",
                award_place: 32,
                award_place_in_team: null,
                games_taken: 25156,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "243542.56",
                bet_cents: 24354255,
                wins: "236188.68",
                win_cents: 23618868,
                points: 0,
                nickname: "Jhonathon",
                award_place: 33,
                award_place_in_team: null,
                games_taken: 67665,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "230491.74",
                bet_cents: 23049174,
                wins: "209706.33",
                win_cents: 20970632,
                points: 0,
                nickname: "Ronald",
                award_place: 34,
                award_place_in_team: null,
                games_taken: 35623,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "230488.14",
                bet_cents: 23048813,
                wins: "206412.15",
                win_cents: 20641214,
                points: 0,
                nickname: "Atken",
                award_place: 35,
                award_place_in_team: null,
                games_taken: 30010,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "228762.42",
                bet_cents: 22876241,
                wins: "211696.22",
                win_cents: 21169622,
                points: 0,
                nickname: "wan hui seah",
                award_place: 36,
                award_place_in_team: null,
                games_taken: 59480,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "220984.32",
                bet_cents: 22098432,
                wins: "214994.80",
                win_cents: 21499480,
                points: 0,
                nickname: "Meric",
                award_place: 37,
                award_place_in_team: null,
                games_taken: 12149,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "220042.95",
                bet_cents: 22004295,
                wins: "230497.62",
                win_cents: 23049762,
                points: 0,
                nickname: "Sam",
                award_place: 38,
                award_place_in_team: null,
                games_taken: 42255,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "217350.97",
                bet_cents: 21735096,
                wins: "216086.58",
                win_cents: 21608657,
                points: 0,
                nickname: "Tiani",
                award_place: 39,
                award_place_in_team: null,
                games_taken: 19630,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "216281.52",
                bet_cents: 21628151,
                wins: "228053.13",
                win_cents: 22805313,
                points: 0,
                nickname: "Rick",
                award_place: 40,
                award_place_in_team: null,
                games_taken: 27338,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "210868.48",
                bet_cents: 21086847,
                wins: "223147.12",
                win_cents: 22314711,
                points: 0,
                nickname: "Graysen",
                award_place: 41,
                award_place_in_team: null,
                games_taken: 18053,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "210739.55",
                bet_cents: 21073955,
                wins: "208822.63",
                win_cents: 20882262,
                points: 0,
                nickname: "TRIGGAMUM",
                award_place: 42,
                award_place_in_team: null,
                games_taken: 42172,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "202568.43",
                bet_cents: 20256842,
                wins: "202773.51",
                win_cents: 20277350,
                points: 0,
                nickname: "David Anthony",
                award_place: 43,
                award_place_in_team: null,
                games_taken: 6895,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "195718.31",
                bet_cents: 19571831,
                wins: "192157.94",
                win_cents: 19215794,
                points: 0,
                nickname: "Ana-Iarmila",
                award_place: 44,
                award_place_in_team: null,
                games_taken: 73017,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "190247.30",
                bet_cents: 19024730,
                wins: "182019.03",
                win_cents: 18201903,
                points: 0,
                nickname: "Sabine",
                award_place: 45,
                award_place_in_team: null,
                games_taken: 16219,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "188185.94",
                bet_cents: 18818593,
                wins: "186290.22",
                win_cents: 18629022,
                points: 0,
                nickname: "Kristy",
                award_place: 46,
                award_place_in_team: null,
                games_taken: 37151,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "187350.11",
                bet_cents: 18735010,
                wins: "194606.06",
                win_cents: 19460606,
                points: 0,
                nickname: "Poker face",
                award_place: 47,
                award_place_in_team: null,
                games_taken: 44820,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "184400.03",
                bet_cents: 18440003,
                wins: "173460.13",
                win_cents: 17346012,
                points: 0,
                nickname: "Tarvinder",
                award_place: 48,
                award_place_in_team: null,
                games_taken: 6386,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "177524.52",
                bet_cents: 17752451,
                wins: "182644.03",
                win_cents: 18264403,
                points: 0,
                nickname: "Paula",
                award_place: 49,
                award_place_in_team: null,
                games_taken: 83188,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "173287.26",
                bet_cents: 17328725,
                wins: "163808.08",
                win_cents: 16380808,
                points: 0,
                nickname: "Achal",
                award_place: 50,
                award_place_in_team: null,
                games_taken: 49457,
                tournament_team_id: null,
            },
        ],
        chargeable_comp_points_budget: {
            source: "0.0",
            parsedValue: 0,
        },
        persistent_comp_points_budget: {
            source: "0.0",
            parsedValue: 0,
        },
        chargeable_comp_points_prize_pool: {
            source: "0.0",
            parsedValue: 0,
        },
        persistent_comp_points_prize_pool: {
            source: "0.0",
            parsedValue: 0,
        },
        money_prize_pool_cents: 762500,
        money_prize_pool: "7625.00",
        winner_team_id: null,
    },
    {
        id: 12321321321,
        title: "Test2",
        user_confirmation_required: false,
        frontend_identifier: "quest--s--test2--ffc",
        strategy: "bet",
        game_category_identity: "pokies",
        start_at: "2024-03-13T00:00:00.000Z",
        end_at: "2025-04-26T23:59:00.000Z",
        finished_at: null,
        currency: "EUR",
        group_tournament: false,
        games_taken_limit: null,
        group_ids: [ 752 ],
        currencies: [
            "EUR",
            "USD",
            "NOK",
            "CAD",
            "NZD",
            "JPY",
            "AUD",
            "BRL",
            "USDC",
            "BTC",
            "ETH",
            "LTC",
            "BCH",
            "DOG",
            "USDT",
            "BNB",
            "TRX",
        ],
        in_progress: true,
        money_budget: "0.00",
        money_budget_cents: 0,
        prizes: [
            {
                id: 32250,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 0,
                nickname: null,
                award_place: 1,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "5000.00",
                money_award_cents: 500000,
            },
            {
                id: 32251,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 2,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "1000.00",
                money_award_cents: 100000,
            },
            {
                id: 32252,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 3,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "700.00",
                money_award_cents: 70000,
            },
            {
                id: 32253,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 4,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "400.00",
                money_award_cents: 40000,
            },
            {
                id: 32254,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 5,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "200.00",
                money_award_cents: 20000,
            },
            {
                id: 32255,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 6,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "150.00",
                money_award_cents: 15000,
            },
            {
                id: 32256,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 7,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "100.00",
                money_award_cents: 10000,
            },
            {
                id: 32257,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 8,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "40.00",
                money_award_cents: 4000,
            },
            {
                id: 32258,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 9,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "20.00",
                money_award_cents: 2000,
            },
            {
                id: 32259,
                stuff: "",
                wager_multiplier: 1,
                freespins_count: 0,
                nickname: null,
                award_place: 10,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "15.00",
                money_award_cents: 1500,
            },
            {
                id: 32260,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 50,
                nickname: null,
                award_place: 11,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32261,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 50,
                nickname: null,
                award_place: 12,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32262,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 30,
                nickname: null,
                award_place: 13,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32263,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 20,
                nickname: null,
                award_place: 14,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
            {
                id: 32264,
                stuff: "",
                wager_multiplier: 0,
                freespins_count: 0,
                nickname: null,
                award_place: 15,
                money_budget_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points: {
                    source: "0.0",
                    parsedValue: 0,
                },
                persistent_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                chargeable_comp_points_percent: {
                    source: "0.0",
                    parsedValue: 0,
                },
                money_award: "0.00",
                money_award_cents: 0,
            },
        ],
        top_players: [
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "1138130.94",
                bet_cents: 113813094,
                wins: "1033438.99",
                win_cents: 103343898,
                points: 0,
                nickname: "Ali",
                award_place: 1,
                award_place_in_team: null,
                games_taken: 161015,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "814102.97",
                bet_cents: 81410296,
                wins: "793333.80",
                win_cents: 79333379,
                points: 0,
                nickname: "David",
                award_place: 2,
                award_place_in_team: null,
                games_taken: 37739,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "674071.91",
                bet_cents: 67407190,
                wins: "666947.82",
                win_cents: 66694781,
                points: 0,
                nickname: "Tracy",
                award_place: 3,
                award_place_in_team: null,
                games_taken: 70579,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "609299.05",
                bet_cents: 60929905,
                wins: "539644.80",
                win_cents: 53964480,
                points: 0,
                nickname: "Mirsada",
                award_place: 4,
                award_place_in_team: null,
                games_taken: 49144,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "583489.49",
                bet_cents: 58348949,
                wins: "555608.22",
                win_cents: 55560822,
                points: 0,
                nickname: "Luckyman",
                award_place: 5,
                award_place_in_team: null,
                games_taken: 25297,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "573769.77",
                bet_cents: 57376977,
                wins: "585774.04",
                win_cents: 58577403,
                points: 0,
                nickname: "Shaneo",
                award_place: 6,
                award_place_in_team: null,
                games_taken: 25353,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "548648.25",
                bet_cents: 54864824,
                wins: "538790.81",
                win_cents: 53879081,
                points: 0,
                nickname: "Barbie",
                award_place: 7,
                award_place_in_team: null,
                games_taken: 33208,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "504818.73",
                bet_cents: 50481873,
                wins: "494795.09",
                win_cents: 49479509,
                points: 0,
                nickname: "Diana",
                award_place: 8,
                award_place_in_team: null,
                games_taken: 51416,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "448403.84",
                bet_cents: 44840384,
                wins: "423017.21",
                win_cents: 42301720,
                points: 0,
                nickname: "Ahmet",
                award_place: 9,
                award_place_in_team: null,
                games_taken: 12716,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "426361.03",
                bet_cents: 42636102,
                wins: "376336.95",
                win_cents: 37633695,
                points: 0,
                nickname: "yun tang",
                award_place: 10,
                award_place_in_team: null,
                games_taken: 20953,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "418853.90",
                bet_cents: 41885390,
                wins: "400558.46",
                win_cents: 40055846,
                points: 0,
                nickname: "Thomas",
                award_place: 11,
                award_place_in_team: null,
                games_taken: 61235,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "401487.74",
                bet_cents: 40148773,
                wins: "409762.75",
                win_cents: 40976275,
                points: 0,
                nickname: "Michael",
                award_place: 12,
                award_place_in_team: null,
                games_taken: 40270,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "392155.44",
                bet_cents: 39215544,
                wins: "390473.17",
                win_cents: 39047317,
                points: 0,
                nickname: "Lachlan",
                award_place: 13,
                award_place_in_team: null,
                games_taken: 29544,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "379418.02",
                bet_cents: 37941802,
                wins: "409834.55",
                win_cents: 40983454,
                points: 0,
                nickname: "Anthony",
                award_place: 14,
                award_place_in_team: null,
                games_taken: 11806,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "346513.90",
                bet_cents: 34651390,
                wins: "372213.07",
                win_cents: 37221307,
                points: 0,
                nickname: "Minhson",
                award_place: 15,
                award_place_in_team: null,
                games_taken: 21606,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "340350.66",
                bet_cents: 34035065,
                wins: "334126.55",
                win_cents: 33412655,
                points: 0,
                nickname: "Scott",
                award_place: 16,
                award_place_in_team: null,
                games_taken: 106403,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "334471.24",
                bet_cents: 33447123,
                wins: "337911.86",
                win_cents: 33791186,
                points: 0,
                nickname: "Tammy7056",
                award_place: 17,
                award_place_in_team: null,
                games_taken: 19347,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "334052.48",
                bet_cents: 33405248,
                wins: "339237.95",
                win_cents: 33923794,
                points: 0,
                nickname: "Andrew",
                award_place: 18,
                award_place_in_team: null,
                games_taken: 25104,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "320977.63",
                bet_cents: 32097762,
                wins: "349122.81",
                win_cents: 34912281,
                points: 0,
                nickname: "Jesus Cristino Burgos",
                award_place: 19,
                award_place_in_team: null,
                games_taken: 11263,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "309564.22",
                bet_cents: 30956422,
                wins: "268708.83",
                win_cents: 26870882,
                points: 0,
                nickname: "Amandeep Singh",
                award_place: 20,
                award_place_in_team: null,
                games_taken: 18144,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "298381.20",
                bet_cents: 29838120,
                wins: "346668.14",
                win_cents: 34666813,
                points: 0,
                nickname: "Nick",
                award_place: 21,
                award_place_in_team: null,
                games_taken: 7094,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "291864.50",
                bet_cents: 29186450,
                wins: "285380.88",
                win_cents: 28538087,
                points: 0,
                nickname: "Rosalyn",
                award_place: 22,
                award_place_in_team: null,
                games_taken: 50638,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "289126.53",
                bet_cents: 28912652,
                wins: "293775.90",
                win_cents: 29377590,
                points: 0,
                nickname: "Coz",
                award_place: 23,
                award_place_in_team: null,
                games_taken: 21988,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "284783.70",
                bet_cents: 28478370,
                wins: "265102.13",
                win_cents: 26510213,
                points: 0,
                nickname: "Jennifer",
                award_place: 24,
                award_place_in_team: null,
                games_taken: 11206,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "284530.71",
                bet_cents: 28453071,
                wins: "282037.00",
                win_cents: 28203700,
                points: 0,
                nickname: "Lindsay",
                award_place: 25,
                award_place_in_team: null,
                games_taken: 17988,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "274011.49",
                bet_cents: 27401149,
                wins: "268258.63",
                win_cents: 26825863,
                points: 0,
                nickname: "Justin",
                award_place: 26,
                award_place_in_team: null,
                games_taken: 15183,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "259179.70",
                bet_cents: 25917969,
                wins: "252036.21",
                win_cents: 25203621,
                points: 0,
                nickname: "Allan",
                award_place: 27,
                award_place_in_team: null,
                games_taken: 16567,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "255872.77",
                bet_cents: 25587277,
                wins: "259138.39",
                win_cents: 25913839,
                points: 0,
                nickname: "Gene",
                award_place: 28,
                award_place_in_team: null,
                games_taken: 12503,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "252536.07",
                bet_cents: 25253606,
                wins: "220261.65",
                win_cents: 22026165,
                points: 0,
                nickname: "Caroline",
                award_place: 29,
                award_place_in_team: null,
                games_taken: 9380,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "251701.41",
                bet_cents: 25170140,
                wins: "266660.13",
                win_cents: 26666012,
                points: 0,
                nickname: "Melissa",
                award_place: 30,
                award_place_in_team: null,
                games_taken: 44852,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "250527.91",
                bet_cents: 25052790,
                wins: "237817.25",
                win_cents: 23781725,
                points: 0,
                nickname: "Spraddy",
                award_place: 31,
                award_place_in_team: null,
                games_taken: 17225,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "246238.17",
                bet_cents: 24623816,
                wins: "249703.53",
                win_cents: 24970353,
                points: 0,
                nickname: "Pamela Hunter",
                award_place: 32,
                award_place_in_team: null,
                games_taken: 25156,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "243542.56",
                bet_cents: 24354255,
                wins: "236188.68",
                win_cents: 23618868,
                points: 0,
                nickname: "Jhonathon",
                award_place: 33,
                award_place_in_team: null,
                games_taken: 67665,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "230491.74",
                bet_cents: 23049174,
                wins: "209706.33",
                win_cents: 20970632,
                points: 0,
                nickname: "Ronald",
                award_place: 34,
                award_place_in_team: null,
                games_taken: 35623,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "230488.14",
                bet_cents: 23048813,
                wins: "206412.15",
                win_cents: 20641214,
                points: 0,
                nickname: "Atken",
                award_place: 35,
                award_place_in_team: null,
                games_taken: 30010,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "228762.42",
                bet_cents: 22876241,
                wins: "211696.22",
                win_cents: 21169622,
                points: 0,
                nickname: "wan hui seah",
                award_place: 36,
                award_place_in_team: null,
                games_taken: 59480,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "220984.32",
                bet_cents: 22098432,
                wins: "214994.80",
                win_cents: 21499480,
                points: 0,
                nickname: "Meric",
                award_place: 37,
                award_place_in_team: null,
                games_taken: 12149,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "220042.95",
                bet_cents: 22004295,
                wins: "230497.62",
                win_cents: 23049762,
                points: 0,
                nickname: "Sam",
                award_place: 38,
                award_place_in_team: null,
                games_taken: 42255,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "217350.97",
                bet_cents: 21735096,
                wins: "216086.58",
                win_cents: 21608657,
                points: 0,
                nickname: "Tiani",
                award_place: 39,
                award_place_in_team: null,
                games_taken: 19630,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "216281.52",
                bet_cents: 21628151,
                wins: "228053.13",
                win_cents: 22805313,
                points: 0,
                nickname: "Rick",
                award_place: 40,
                award_place_in_team: null,
                games_taken: 27338,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "210868.48",
                bet_cents: 21086847,
                wins: "223147.12",
                win_cents: 22314711,
                points: 0,
                nickname: "Graysen",
                award_place: 41,
                award_place_in_team: null,
                games_taken: 18053,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "210739.55",
                bet_cents: 21073955,
                wins: "208822.63",
                win_cents: 20882262,
                points: 0,
                nickname: "TRIGGAMUM",
                award_place: 42,
                award_place_in_team: null,
                games_taken: 42172,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "202568.43",
                bet_cents: 20256842,
                wins: "202773.51",
                win_cents: 20277350,
                points: 0,
                nickname: "David Anthony",
                award_place: 43,
                award_place_in_team: null,
                games_taken: 6895,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "195718.31",
                bet_cents: 19571831,
                wins: "192157.94",
                win_cents: 19215794,
                points: 0,
                nickname: "Ana-Iarmila",
                award_place: 44,
                award_place_in_team: null,
                games_taken: 73017,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "190247.30",
                bet_cents: 19024730,
                wins: "182019.03",
                win_cents: 18201903,
                points: 0,
                nickname: "Sabine",
                award_place: 45,
                award_place_in_team: null,
                games_taken: 16219,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "188185.94",
                bet_cents: 18818593,
                wins: "186290.22",
                win_cents: 18629022,
                points: 0,
                nickname: "Kristy",
                award_place: 46,
                award_place_in_team: null,
                games_taken: 37151,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "187350.11",
                bet_cents: 18735010,
                wins: "194606.06",
                win_cents: 19460606,
                points: 0,
                nickname: "Poker face",
                award_place: 47,
                award_place_in_team: null,
                games_taken: 44820,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "184400.03",
                bet_cents: 18440003,
                wins: "173460.13",
                win_cents: 17346012,
                points: 0,
                nickname: "Tarvinder",
                award_place: 48,
                award_place_in_team: null,
                games_taken: 6386,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "177524.52",
                bet_cents: 17752451,
                wins: "182644.03",
                win_cents: 18264403,
                points: 0,
                nickname: "Paula",
                award_place: 49,
                award_place_in_team: null,
                games_taken: 83188,
                tournament_team_id: null,
            },
            {
                tournament_id: 1564,
                user_confirmed: null,
                rate: {
                    source: "0.0",
                    parsedValue: 0,
                },
                bets: "173287.26",
                bet_cents: 17328725,
                wins: "163808.08",
                win_cents: 16380808,
                points: 0,
                nickname: "Achal",
                award_place: 50,
                award_place_in_team: null,
                games_taken: 49457,
                tournament_team_id: null,
            },
        ],
        chargeable_comp_points_budget: {
            source: "0.0",
            parsedValue: 0,
        },
        persistent_comp_points_budget: {
            source: "0.0",
            parsedValue: 0,
        },
        chargeable_comp_points_prize_pool: {
            source: "0.0",
            parsedValue: 0,
        },
        persistent_comp_points_prize_pool: {
            source: "0.0",
            parsedValue: 0,
        },
        money_prize_pool_cents: 762500,
        money_prize_pool: "7625.00",
        winner_team_id: null,
    },
];
