import {ILogoConfig} from "./logo";

export * from "./vipAdventuresDTO";
export * from "./performanceDTO";
export * from "./gifts";
export * from "./cashbox";
export * from "./lotteriesDTO";
export * from "./metrics";
export * from "./playerDTO";
export * from "./couponePromoCodes";
export * from "./CMS";
export * from "./compPoints";
export * from "./gamesDTO";
export * from "./info";
export * from "./jackpot";
export * from "./lootboxes";
export * from "./multilang";
export * from "./tournamentsDTO";
export * from "./logo";
