export enum IbizaKeysValidation {
    BLACKLISTED = "IBIZA::INVALID::BLACKLISTED",
    INVALID_DOMAIN = "IBIZA::INVALID::INVALID_DOMAIN",
    REJECTED_EMAIL = "IBIZA::INVALID::REJECTED_EMAIL",
    RISKY = "IBIZA::RISKY::RISKY",
    NON_PERSONAL = "IBIZA::RISKY::NON_PERSONAL",
    INBOX_FULL = "IBIZA::RISKY::INBOX_FULL",
    TEMPORARY = "IBIZA::RISKY::TEMPORARY",
    TIMEOUT = "IBIZA::RISKY::TIMEOUT",
    ACCEPTED_EMAIL = "IBIZA::VALID::ACCEPTED_EMAIL",
    WHITELISTED = "IBIZA::VALID::WHITELISTED",
}
